In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("hello")

In [3]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
world = tf.constant("world")

In [14]:
tensor_a=tf.constant([3,4], dtype=tf.int32)  
 



In [15]:
tensor_b=tf.constant([[1,2]], dtype=tf.int32) 

In [16]:
tensor_add=tf.add(tensor_a, tensor_b)

In [17]:
print(tensor_add)  

Tensor("Add_1:0", shape=(1, 2), dtype=int32)


In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
with tf.Session() as sess:
    result=sess.run(hello)

In [6]:
print(result)

b'hello'


In [7]:
a = tf.constant(10)
b= tf.constant(20)

In [8]:
add = a + b
mul = a*b

In [9]:
sess =tf.Session()
result_add=sess.run(add)
result1 = sess.run(mul)

In [10]:
print(result_add)
print(result1)

30
200


In [11]:
N = tf.constant("N")
I = tf.constant("I")
K = tf.constant("K")
H = tf.constant("H")
I = tf.constant("I")
T = tf.constant("T")
H = tf.constant("H")
A = tf.constant("A")

a = [N,I,K,H,I,T,H,A]

In [12]:
sess = tf.InteractiveSession()
for i in a:
    print(i.eval())
    #print(sess.run(i))
    #print("\n")

b'N'
b'I'
b'K'
b'H'
b'I'
b'T'
b'H'
b'A'


In [13]:
 a = tf.ones((4,4))
 b = tf.random_uniform((4,4))

In [14]:
print(a)

Tensor("ones:0", shape=(4, 4), dtype=float32)


In [15]:
sess = tf.InteractiveSession()

E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\client\session.py:1735: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [16]:
print(a.eval())
print(b.eval())

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.42377937 0.7019838  0.676643   0.55981255]
 [0.8333199  0.43774486 0.24844944 0.083125  ]
 [0.56579924 0.86666715 0.29962194 0.96598816]
 [0.26010013 0.21750677 0.17523324 0.27055883]]


In [17]:
my_tensor = tf.random_uniform((4,4),0,1)
print(sess.run(my_tensor))

[[9.9059367e-01 5.7019567e-01 4.8022449e-01 5.1703072e-01]
 [7.0485830e-01 8.9653575e-01 1.3021827e-02 7.1396947e-02]
 [6.9214427e-01 1.7988682e-04 7.0877504e-01 7.1010101e-01]
 [5.1612651e-01 5.5239093e-01 1.6991091e-01 8.4046638e-01]]


In [18]:
 my_var = tf.Variable(4)

In [19]:
my_var

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [20]:
init = tf.global_variables_initializer()
sess.run(init)
sess.run(my_var)

4

In [21]:
my_ph = tf.placeholder(tf.float32)

In [22]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [23]:
np.random.seed(101)
tf.set_random_seed(101)

In [24]:
rand_a = np.random.uniform(0,100,(5,5))

In [25]:
rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [26]:
rand_b = np.random.uniform(0,100,(5,1))

In [27]:
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [28]:
a = tf.placeholder(tf.float32)

In [29]:
b=tf.placeholder(tf.float32)

In [30]:
add_op = a+b

In [31]:
add_op

<tf.Tensor 'add_1:0' shape=<unknown> dtype=float32>

In [32]:
sess =tf.InteractiveSession()
sess.run(add_op,feed_dict = {a:10, b:20})


30.0

In [33]:
mul_op = a*b
sess.run(mul_op, feed_dict = {a:rand_a, b:rand_b})

array([[5134.644  , 5674.25   ,  283.12433, 1705.4707 , 6813.8315 ],
       [4341.8125 , 1598.267  , 4652.734  , 3756.8293 ,  988.94635],
       [3207.8113 , 2038.1029 , 1052.7742 , 4546.9805 , 5588.1157 ],
       [1707.379  ,  614.02527, 4434.989  , 5356.7773 , 2029.8555 ],
       [3714.0984 , 2806.6438 ,  262.76764,  747.19855, 1013.292  ]],
      dtype=float32)

In [34]:
x = tf.placeholder(tf.float32,(None,10))

In [35]:
sess.run(x)

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_3' with dtype float and shape [?,10]
	 [[node Placeholder_3 (defined at <ipython-input-34-af6acca743ac>:1) ]]

Original stack trace for 'Placeholder_3':
  File "E:\nikhitha\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\nikhitha\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "E:\nikhitha\Anaconda\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "E:\nikhitha\Anaconda\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "E:\nikhitha\Anaconda\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "E:\nikhitha\Anaconda\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 370, in dispatch_queue
    yield self.process_one()
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 708, in __init__
    self.run()
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "E:\nikhitha\Anaconda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "E:\nikhitha\Anaconda\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "E:\nikhitha\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "E:\nikhitha\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "E:\nikhitha\Anaconda\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "E:\nikhitha\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "E:\nikhitha\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "E:\nikhitha\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-af6acca743ac>", line 1, in <module>
    x = tf.placeholder(tf.float32,(None,10))
  File "E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7400, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "E:\nikhitha\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


In [ ]:
b = tf.Variable(tf.random_normal([10,3]))

In [ ]:
b

In [ ]:
init = tf.global_variables_initializer()

In [ ]:
sess.run(init)

In [ ]:
print(sess.run(b))